# Generated by Django 2.1.7 on 2019-04-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('class_ID', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('role_ID', models.IntegerField()),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
