# Generated by Django 2.1.7 on 2019-04-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_text',
            field=models.CharField(default='empty', max_length=35),
        ),
    ]
