# Generated by Django 2.1.7 on 2019-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_mail_mail_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_text',
            field=models.EmailField(max_length=224),
        ),
    ]
