# Generated by Django 2.1.7 on 2019-04-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190404_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='mail_text',
        ),
        migrations.AddField(
            model_name='mail',
            name='address',
            field=models.EmailField(default='null@null.com', max_length=254),
        ),
    ]
