# Generated by Django 2.1.7 on 2019-04-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190405_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
