# Generated by Django 2.1.7 on 2019-04-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Role'),
        ),
    ]
