# Generated by Django 2.1.7 on 2019-04-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190405_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('organizers', models.CharField(max_length=512)),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('school_year', models.CharField(default='2018-2019', max_length=50, verbose_name='Năm học')),
                ('discription', models.TextField(verbose_name='Mô tả hoạt động')),
                ('point', models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='roleName',
        ),
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='', max_length=100, verbose_name='Tên vai trò'),
        ),
    ]
