# Generated by Django 2.1.7 on 2019-04-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190405_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên hoạt động'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organizers',
            field=models.CharField(max_length=512, verbose_name='Ban tổ chức'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='point',
            field=models.SmallIntegerField(verbose_name='Điểm'),
        ),
    ]
