# Generated by Django 2.1.7 on 2019-04-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190405_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
