# Generated by Django 2.1.7 on 2019-04-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190405_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
