# Generated by Django 2.1.7 on 2019-04-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190407_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Activity'),
        ),
    ]
