# Generated by Django 2.1.7 on 2019-04-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20190407_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
