# Generated by Django 2.1.7 on 2019-04-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20190407_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
