# Generated by Django 2.1.7 on 2019-04-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20190407_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='address',
            new_name='mail_address',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='mail',
            new_name='user',
        ),
    ]
