# Generated by Django 2.1.7 on 2019-04-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20190407_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(to='login.User'),
        ),
    ]
