# Generated by Django 2.1.7 on 2019-04-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_activity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='discription',
            new_name='description',
        ),
    ]
