# Generated by Django 2.1.7 on 2019-04-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_remove_activity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_ID',
            new_name='role',
        ),
    ]
