# Generated by Django 2.1.7 on 2019-04-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20190407_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acctivities',
            field=models.ManyToManyField(to='login.Activity'),
        ),
    ]
