# Generated by Django 2.1.7 on 2019-04-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_user_acctivities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acctivities',
        ),
        migrations.AddField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(to='login.Activity'),
        ),
    ]
