# Generated by Django 2.1.7 on 2019-04-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_auto_20190408_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(null=True, to='login.Activity'),
        ),
    ]
