# Generated by Django 2.1.7 on 2019-04-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_auto_20190409_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(blank=True, editable=False, to='login.Activity'),
        ),
    ]
