# Generated by Django 2.1.7 on 2019-04-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_checkedacitvity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckedAcitvity',
            new_name='CheckedActivity',
        ),
    ]
