# Generated by Django 2.1.7 on 2019-04-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_auto_20190410_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedactivity',
            name='acitvity_ID',
        ),
        migrations.AddField(
            model_name='checkedactivity',
            name='acitvity',
            field=models.ManyToManyField(to='login.Activity'),
        ),
        migrations.RemoveField(
            model_name='checkedactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='checkedactivity',
            name='user',
            field=models.ManyToManyField(to='login.User'),
        ),
    ]
