# Generated by Django 2.1.7 on 2019-04-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_auto_20190410_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedactivity',
            name='acitvities',
        ),
        migrations.RemoveField(
            model_name='checkedactivity',
            name='users',
        ),
    ]
