# Generated by Django 2.1.7 on 2019-04-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20190410_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckedActivity',
        ),
    ]
