# Generated by Django 2.1.7 on 2019-04-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_delete_checkedactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedActivity',
            fields=[
                ('activity_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='checked_activities',
            field=models.ManyToManyField(editable=False, to='login.CheckedActivity'),
        ),
    ]
