# Generated by Django 2.1.7 on 2019-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_auto_20190410_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accumulated_point',
            field=models.IntegerField(default=69, verbose_name='Điểm chuyên cần'),
        ),
    ]
