# Generated by Django 2.1.7 on 2019-04-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_auto_20190411_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='semester',
            field=models.SmallIntegerField(default=1, verbose_name='Học kỳ'),
        ),
    ]
