# Generated by Django 2.1.7 on 2019-04-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_auto_20190411_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên hoạt động'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='Sinh viên', max_length=100, unique=True, verbose_name='Tên vai trò'),
        ),
    ]
