# Generated by Django 2.1.7 on 2019-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0045_auto_20190411_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Hoạt động', 'verbose_name_plural': 'Hoạt động'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Vai trò', 'verbose_name_plural': 'Vai trò'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_register',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
    ]
