# Generated by Django 2.1.7 on 2019-04-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0046_auto_20190418_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_of_register',
        ),
    ]
