# Generated by Django 2.1.7 on 2019-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0047_remove_user_number_of_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='number_of_register',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
    ]
