# Generated by Django 2.1.7 on 2019-04-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0050_auto_20190418_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_date'], 'verbose_name': 'Hoạt động', 'verbose_name_plural': 'Hoạt động'},
        ),
    ]
