# Generated by Django 2.2.1 on 2019-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0051_auto_20190418_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPdfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='announcements/%Y/%m/%d')),
            ],
        ),
    ]
