# Generated by Django 2.2.1 on 2019-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0052_uploadpdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_address',
            field=models.EmailField(default='a@b.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadpdffile',
            name='pdf_file',
            field=models.FileField(editable=False, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accumulated_point',
            field=models.IntegerField(default=60, verbose_name='Điểm chuyên cần'),
        ),
    ]
