# Generated by Django 3.0.8 on 2020-08-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên hoạt động')),
                ('organizers', models.CharField(max_length=512, verbose_name='Ban tổ chức')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('school_year', models.CharField(default='2019-2020', max_length=50, verbose_name='Năm học')),
                ('semester', models.SmallIntegerField(choices=[(1, 'HỌC KỲ 1'), (2, 'HỌC KỲ 2')], verbose_name='Học kỳ')),
                ('description', models.TextField(verbose_name='Mô tả hoạt động')),
                ('point', models.SmallIntegerField(verbose_name='Điểm')),
                ('number_of_register', models.SmallIntegerField(default=0, editable=False, verbose_name='Số lượng dăng ký')),
                ('is_approved', models.BooleanField(default=False, help_text='Được user với quyền giáo viên approved!')),
            ],
            options={
                'verbose_name': 'Hoạt động',
                'verbose_name_plural': 'Hoạt động',
                'db_table': 'youth_union_Activity',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_date', models.DateField(auto_now_add=True, help_text='Ngày điểm danh')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth_union.Activity')),
            ],
            options={
                'verbose_name': 'Hoạt động đã điểm danh',
                'verbose_name_plural': 'Hoạt động đã điểm danh',
                'db_table': 'youth_union_CheckActivity',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung bình luận')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Ngày giờ bình luận')),
            ],
            options={
                'db_table': 'youth_union_Comment',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề thông báo', max_length=1024)),
                ('content', models.TextField(help_text='Nội dung thông báo')),
                ('slug', models.SlugField(max_length=1024)),
            ],
            options={
                'db_table': 'youth_union_Message',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_ID', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Tên vai trò')),
            ],
            options={
                'verbose_name': 'Vai trò',
                'verbose_name_plural': 'Vai trò',
                'db_table': 'youth_union_Role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Sinh viên ID')),
                ('class_ID', models.CharField(max_length=12, verbose_name='Lớp ID')),
                ('name', models.CharField(max_length=25, verbose_name='Tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('password', models.CharField(max_length=256, verbose_name='Mật khẩu')),
                ('accumulated_point', models.IntegerField(default=60, verbose_name='Điểm chuyên cần')),
                ('activities', models.ManyToManyField(blank=True, editable=False, related_name='users_join_to', to='youth_union.Activity')),
                ('checked_activities', models.ManyToManyField(editable=False, related_name='was_checked_by', through='youth_union.CheckActivity', to='youth_union.Activity')),
                ('comments', models.ManyToManyField(related_name='who_comments', through='youth_union.Comment', to='youth_union.Message')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth_union.Role', verbose_name='Vai trò')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'youth_union_User',
            },
        ),
        migrations.CreateModel(
            name='UploadPdfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(editable=False, upload_to='announcements/')),
                ('owner', models.ForeignKey(help_text='Ai đăng file thông báo', on_delete=django.db.models.deletion.DO_NOTHING, to='youth_union.User')),
            ],
            options={
                'db_table': 'youth_union_UploadPdfFile',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(help_text='Ai là nguời đăng thông báo?', on_delete=django.db.models.deletion.CASCADE, to='youth_union.User'),
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.EmailField(default='a@b.com', max_length=254, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth_union.User')),
            ],
            options={
                'db_table': 'youth_union_Mail',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth_union.Message'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth_union.User'),
        ),
        migrations.AddField(
            model_name='checkactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth_union.User'),
        ),
    ]
