# Generated by Django 3.0.8 on 2020-08-15 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youth_union', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Ngày giờ đăng bài viết'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã hoạt động'),
        ),
    ]
