# Generated by Django 3.0.8 on 2020-08-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_union', '0002_auto_20200816_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='limit_register_day',
            field=models.SmallIntegerField(default=3, help_text='Giới hạn số ngày được đăng ký'),
        ),
    ]
