# Generated by Django 3.0.8 on 2020-09-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_union', '0003_activity_limit_register_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='number_of_joined',
            field=models.SmallIntegerField(default=0, editable=False, verbose_name='Số lượng tham gia'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='limit_register_day',
            field=models.SmallIntegerField(default=3, help_text='Giới hạn số ngày được đăng ký', verbose_name='Mở đăng ký trước ngày bắt đầu'),
        ),
    ]
